repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    additional_dependencies:
      - "toml>=0.10"
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: flake8
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude: .*\.md$