###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from esque_wire.protocol.constants import (
    AclOperation,
    AclPermissionType,
    ApiKey,
    ErrorCode,
    ResourcePatternType,
    ResourceType,
)
from esque_wire.protocol.serializers.generic import EnumSerializer, OptionalEnumSerializer
from esque_wire.protocol.serializers.primitive import int8Serializer, int16Serializer

apiKeySerializer = OptionalEnumSerializer(ApiKey, int16Serializer)
aclOperationSerializer = EnumSerializer(AclOperation, int8Serializer)
resourceTypeSerializer = EnumSerializer(ResourceType, int8Serializer)
aclPermissionTypeSerializer = EnumSerializer(AclPermissionType, int8Serializer)
resourcePatternTypeSerializer = EnumSerializer(ResourcePatternType, int8Serializer)
errorCodeSerializer = EnumSerializer(ErrorCode, int16Serializer)
