##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.add_offsets_to_txn_request import AddOffsetsToTxnRequestData

from ._main_serializers import ClassSerializer, Schema, int16Serializer, int64Serializer, stringSerializer


addOffsetsToTxnRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("transactional_id", stringSerializer),
        ("producer_id", int64Serializer),
        ("producer_epoch", int16Serializer),
        ("group_id", stringSerializer),
    ],
    1: [
        ("transactional_id", stringSerializer),
        ("producer_id", int64Serializer),
        ("producer_epoch", int16Serializer),
        ("group_id", stringSerializer),
    ],
}


addOffsetsToTxnRequestDataSerializers: Dict[int, ClassSerializer[AddOffsetsToTxnRequestData]] = {
    version: ClassSerializer(AddOffsetsToTxnRequestData, schema)
    for version, schema in addOffsetsToTxnRequestDataSchemas.items()
}

addOffsetsToTxnRequestDataSerializers[-1] = addOffsetsToTxnRequestDataSerializers[1]
