##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.add_offsets_to_txn_response import (
    AddOffsetsToTxnResponseData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    Schema,
    int16Serializer,
    int32Serializer,
)


addOffsetsToTxnResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
    ],
    1: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
    ],
}


addOffsetsToTxnResponseDataSerializers: Dict[int, DataClassSerializer[AddOffsetsToTxnResponseData]] = {
    version: DataClassSerializer(AddOffsetsToTxnResponseData, schema) for version, schema
    in addOffsetsToTxnResponseDataSchemas.items()
}

