###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.alter_replica_log_dirs_request import AlterReplicaLogDirsRequestData, LogDir, Topic
from ._main_serializers import ArraySerializer, ClassSerializer, Schema, int32Serializer, stringSerializer

topicSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("partitions", ArraySerializer(int32Serializer))],
    1: [("topic", stringSerializer), ("partitions", ArraySerializer(int32Serializer))],
}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[1]


logDirSchemas: Dict[int, Schema] = {
    0: [("log_dir", stringSerializer), ("topics", ArraySerializer(topicSerializers[0]))],
    1: [("log_dir", stringSerializer), ("topics", ArraySerializer(topicSerializers[1]))],
}


logDirSerializers: Dict[int, ClassSerializer[LogDir]] = {
    version: ClassSerializer(LogDir, schema) for version, schema in logDirSchemas.items()
}

logDirSerializers[-1] = logDirSerializers[1]


alterReplicaLogDirsRequestDataSchemas: Dict[int, Schema] = {
    0: [("log_dirs", ArraySerializer(logDirSerializers[0]))],
    1: [("log_dirs", ArraySerializer(logDirSerializers[1]))],
}


alterReplicaLogDirsRequestDataSerializers: Dict[int, ClassSerializer[AlterReplicaLogDirsRequestData]] = {
    version: ClassSerializer(AlterReplicaLogDirsRequestData, schema)
    for version, schema in alterReplicaLogDirsRequestDataSchemas.items()
}

alterReplicaLogDirsRequestDataSerializers[-1] = alterReplicaLogDirsRequestDataSerializers[1]
