##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.alter_replica_log_dirs_response import (
    AlterReplicaLogDirsResponseData,
    Partition,
    Topic,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int16Serializer,
    int32Serializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [("partition", int32Serializer), ("error_code", int16Serializer)],
    1: [("partition", int32Serializer), ("error_code", int16Serializer)],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


topicSchemas: Dict[int, Schema] = {
    0: [
        ("topic", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("topic", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
}


topicSerializers: Dict[int, DataClassSerializer[Topic]] = {
    version: DataClassSerializer(Topic, schema)
    for version, schema in topicSchemas.items()
}


alterReplicaLogDirsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("throttle_time_ms", int32Serializer),
        ("topics", ArraySerializer(topicSerializers[0])),
    ],
    1: [
        ("throttle_time_ms", int32Serializer),
        ("topics", ArraySerializer(topicSerializers[1])),
    ],
}


alterReplicaLogDirsResponseDataSerializers: Dict[
    int, DataClassSerializer[AlterReplicaLogDirsResponseData]
] = {
    version: DataClassSerializer(AlterReplicaLogDirsResponseData, schema)
    for version, schema in alterReplicaLogDirsResponseDataSchemas.items()
}
