###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.alter_configs_request import AlterConfigsRequestData, ConfigEntry, Resource
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    booleanSerializer,
    nullableStringSerializer,
    resourceTypeSerializer,
    stringSerializer,
)

configEntrySchemas: Dict[int, Schema] = {
    0: [("config_name", stringSerializer), ("config_value", nullableStringSerializer)],
    1: [("config_name", stringSerializer), ("config_value", nullableStringSerializer)],
}


configEntrySerializers: Dict[int, ClassSerializer[ConfigEntry]] = {
    version: ClassSerializer(ConfigEntry, schema) for version, schema in configEntrySchemas.items()
}

configEntrySerializers[-1] = configEntrySerializers[1]


resourceSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("config_entries", ArraySerializer(configEntrySerializers[0])),
    ],
    1: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("config_entries", ArraySerializer(configEntrySerializers[1])),
    ],
}


resourceSerializers: Dict[int, ClassSerializer[Resource]] = {
    version: ClassSerializer(Resource, schema) for version, schema in resourceSchemas.items()
}

resourceSerializers[-1] = resourceSerializers[1]


alterConfigsRequestDataSchemas: Dict[int, Schema] = {
    0: [("resources", ArraySerializer(resourceSerializers[0])), ("validate_only", booleanSerializer)],
    1: [("resources", ArraySerializer(resourceSerializers[1])), ("validate_only", booleanSerializer)],
}


alterConfigsRequestDataSerializers: Dict[int, ClassSerializer[AlterConfigsRequestData]] = {
    version: ClassSerializer(AlterConfigsRequestData, schema)
    for version, schema in alterConfigsRequestDataSchemas.items()
}

alterConfigsRequestDataSerializers[-1] = alterConfigsRequestDataSerializers[1]
