##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.controlled_shutdown_request import ControlledShutdownRequestData

from ._main_serializers import (
    DataClassSerializer,
    DummySerializer,
    Schema,
    int32Serializer,
    int64Serializer,
)


controlledShutdownRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("broker_id", int32Serializer),
        ("broker_epoch", DummySerializer(int64Serializer.default)),
    ],
    1: [
        ("broker_id", int32Serializer),
        ("broker_epoch", DummySerializer(int64Serializer.default)),
    ],
    2: [("broker_id", int32Serializer), ("broker_epoch", int64Serializer)],
}


controlledShutdownRequestDataSerializers: Dict[
    int, DataClassSerializer[ControlledShutdownRequestData]
] = {
    version: DataClassSerializer(ControlledShutdownRequestData, schema)
    for version, schema in controlledShutdownRequestDataSchemas.items()
}
