##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.create_topics_response import CreateTopicsResponseData, Topic

from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    nullableStringSerializer,
    stringSerializer,
)


topicSchemas: Dict[int, Schema] = {
    0: [
        ("name", stringSerializer),
        ("error_code", errorCodeSerializer),
        ("error_message", DummySerializer(nullableStringSerializer.default)),
    ],
    1: [("name", stringSerializer), ("error_code", errorCodeSerializer), ("error_message", nullableStringSerializer)],
    2: [("name", stringSerializer), ("error_code", errorCodeSerializer), ("error_message", nullableStringSerializer)],
    3: [("name", stringSerializer), ("error_code", errorCodeSerializer), ("error_message", nullableStringSerializer)],
}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[3]


createTopicsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("topics", ArraySerializer(topicSerializers[0])),
        ("throttle_time_ms", DummySerializer(int32Serializer.default)),
    ],
    1: [
        ("topics", ArraySerializer(topicSerializers[1])),
        ("throttle_time_ms", DummySerializer(int32Serializer.default)),
    ],
    2: [("throttle_time_ms", int32Serializer), ("topics", ArraySerializer(topicSerializers[2]))],
    3: [("throttle_time_ms", int32Serializer), ("topics", ArraySerializer(topicSerializers[3]))],
}


createTopicsResponseDataSerializers: Dict[int, ClassSerializer[CreateTopicsResponseData]] = {
    version: ClassSerializer(CreateTopicsResponseData, schema)
    for version, schema in createTopicsResponseDataSchemas.items()
}

createTopicsResponseDataSerializers[-1] = createTopicsResponseDataSerializers[3]
