##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.create_acls_request import CreateAclsRequestData, Creation
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    aclOperationSerializer,
    aclPermissionTypeSerializer,
    int8Serializer,
    resourceTypeSerializer,
    stringSerializer,
)

creationSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
        ("resource_pattern_type", DummySerializer(3)),
    ],
    1: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("resource_pattern_type", int8Serializer),
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
    ],
}


creationSerializers: Dict[int, ClassSerializer[Creation]] = {
    version: ClassSerializer(Creation, schema) for version, schema in creationSchemas.items()
}

creationSerializers[-1] = creationSerializers[1]


createAclsRequestDataSchemas: Dict[int, Schema] = {
    0: [("creations", ArraySerializer(creationSerializers[0]))],
    1: [("creations", ArraySerializer(creationSerializers[1]))],
}


createAclsRequestDataSerializers: Dict[int, ClassSerializer[CreateAclsRequestData]] = {
    version: ClassSerializer(CreateAclsRequestData, schema) for version, schema in createAclsRequestDataSchemas.items()
}

createAclsRequestDataSerializers[-1] = createAclsRequestDataSerializers[1]
