###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.create_acls_response import CreateAclsResponseData, CreationResponse
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    nullableStringSerializer,
)

creationResponseSchemas: Dict[int, Schema] = {
    0: [("error_code", errorCodeSerializer), ("error_message", nullableStringSerializer)],
    1: [("error_code", errorCodeSerializer), ("error_message", nullableStringSerializer)],
}


creationResponseSerializers: Dict[int, ClassSerializer[CreationResponse]] = {
    version: ClassSerializer(CreationResponse, schema) for version, schema in creationResponseSchemas.items()
}

creationResponseSerializers[-1] = creationResponseSerializers[1]


createAclsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("throttle_time_ms", int32Serializer),
        ("creation_responses", ArraySerializer(creationResponseSerializers[0])),
    ],
    1: [
        ("throttle_time_ms", int32Serializer),
        ("creation_responses", ArraySerializer(creationResponseSerializers[1])),
    ],
}


createAclsResponseDataSerializers: Dict[int, ClassSerializer[CreateAclsResponseData]] = {
    version: ClassSerializer(CreateAclsResponseData, schema)
    for version, schema in createAclsResponseDataSchemas.items()
}

createAclsResponseDataSerializers[-1] = createAclsResponseDataSerializers[1]
