##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.create_partitions_request import CreatePartitionsRequestData, NewPartitions, TopicPartition

from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    booleanSerializer,
    int32Serializer,
    stringSerializer,
)


newPartitionsSchemas: Dict[int, Schema] = {
    0: [("count", int32Serializer), ("assignment", ArraySerializer(ArraySerializer(int32Serializer)))],
    1: [("count", int32Serializer), ("assignment", ArraySerializer(ArraySerializer(int32Serializer)))],
}


newPartitionsSerializers: Dict[int, ClassSerializer[NewPartitions]] = {
    version: ClassSerializer(NewPartitions, schema) for version, schema in newPartitionsSchemas.items()
}

newPartitionsSerializers[-1] = newPartitionsSerializers[1]


topicPartitionSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("new_partitions", newPartitionsSerializers[0])],
    1: [("topic", stringSerializer), ("new_partitions", newPartitionsSerializers[1])],
}


topicPartitionSerializers: Dict[int, ClassSerializer[TopicPartition]] = {
    version: ClassSerializer(TopicPartition, schema) for version, schema in topicPartitionSchemas.items()
}

topicPartitionSerializers[-1] = topicPartitionSerializers[1]


createPartitionsRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("topic_partitions", ArraySerializer(topicPartitionSerializers[0])),
        ("timeout", int32Serializer),
        ("validate_only", booleanSerializer),
    ],
    1: [
        ("topic_partitions", ArraySerializer(topicPartitionSerializers[1])),
        ("timeout", int32Serializer),
        ("validate_only", booleanSerializer),
    ],
}


createPartitionsRequestDataSerializers: Dict[int, ClassSerializer[CreatePartitionsRequestData]] = {
    version: ClassSerializer(CreatePartitionsRequestData, schema)
    for version, schema in createPartitionsRequestDataSchemas.items()
}

createPartitionsRequestDataSerializers[-1] = createPartitionsRequestDataSerializers[1]
