##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.delete_records_response import (
    DeleteRecordsResponseData,
    Partition,
    Topic,
)

from ._main_serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    int64Serializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [
        ("partition", int32Serializer),
        ("low_watermark", int64Serializer),
        ("error_code", errorCodeSerializer),
    ],
    1: [
        ("partition", int32Serializer),
        ("low_watermark", int64Serializer),
        ("error_code", errorCodeSerializer),
    ],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


topicSchemas: Dict[int, Schema] = {
    0: [
        ("topic", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("topic", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
}


topicSerializers: Dict[int, DataClassSerializer[Topic]] = {
    version: DataClassSerializer(Topic, schema)
    for version, schema in topicSchemas.items()
}


deleteRecordsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("throttle_time_ms", int32Serializer),
        ("topics", ArraySerializer(topicSerializers[0])),
    ],
    1: [
        ("throttle_time_ms", int32Serializer),
        ("topics", ArraySerializer(topicSerializers[1])),
    ],
}


deleteRecordsResponseDataSerializers: Dict[
    int, DataClassSerializer[DeleteRecordsResponseData]
] = {
    version: DataClassSerializer(DeleteRecordsResponseData, schema)
    for version, schema in deleteRecordsResponseDataSchemas.items()
}
