###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.delete_records_request import DeleteRecordsRequestData, Partition, Topic
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    int32Serializer,
    int64Serializer,
    stringSerializer,
)

partitionSchemas: Dict[int, Schema] = {
    0: [("partition", int32Serializer), ("offset", int64Serializer)],
    1: [("partition", int32Serializer), ("offset", int64Serializer)],
}


partitionSerializers: Dict[int, ClassSerializer[Partition]] = {
    version: ClassSerializer(Partition, schema) for version, schema in partitionSchemas.items()
}

partitionSerializers[-1] = partitionSerializers[1]


topicSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[0]))],
    1: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[1]))],
}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[1]


deleteRecordsRequestDataSchemas: Dict[int, Schema] = {
    0: [("topics", ArraySerializer(topicSerializers[0])), ("timeout", int32Serializer)],
    1: [("topics", ArraySerializer(topicSerializers[1])), ("timeout", int32Serializer)],
}


deleteRecordsRequestDataSerializers: Dict[int, ClassSerializer[DeleteRecordsRequestData]] = {
    version: ClassSerializer(DeleteRecordsRequestData, schema)
    for version, schema in deleteRecordsRequestDataSchemas.items()
}

deleteRecordsRequestDataSerializers[-1] = deleteRecordsRequestDataSerializers[1]
