##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.delete_acls_request import DeleteAclsRequestData, Filter

from ._main_serializers import (
    ArraySerializer,
    DataClassSerializer,
    DummySerializer,
    Schema,
    aclOperationSerializer,
    aclPermissionTypeSerializer,
    int8Serializer,
    nullableStringSerializer,
    resourceTypeSerializer,
)


filterSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", nullableStringSerializer),
        ("principal", nullableStringSerializer),
        ("host", nullableStringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
        ("resource_pattern_type_filter", DummySerializer(3)),
    ],
    1: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", nullableStringSerializer),
        ("resource_pattern_type_filter", int8Serializer),
        ("principal", nullableStringSerializer),
        ("host", nullableStringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
    ],
}


filterSerializers: Dict[int, DataClassSerializer[Filter]] = {
    version: DataClassSerializer(Filter, schema)
    for version, schema in filterSchemas.items()
}


deleteAclsRequestDataSchemas: Dict[int, Schema] = {
    0: [("filters", ArraySerializer(filterSerializers[0]))],
    1: [("filters", ArraySerializer(filterSerializers[1]))],
}


deleteAclsRequestDataSerializers: Dict[
    int, DataClassSerializer[DeleteAclsRequestData]
] = {
    version: DataClassSerializer(DeleteAclsRequestData, schema)
    for version, schema in deleteAclsRequestDataSchemas.items()
}
