###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.delete_acls_response import DeleteAclsResponseData, FilterResponse, MatchingAcl
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    aclOperationSerializer,
    aclPermissionTypeSerializer,
    errorCodeSerializer,
    int8Serializer,
    int32Serializer,
    nullableStringSerializer,
    resourceTypeSerializer,
    stringSerializer,
)

matchingAclSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
        ("resource_pattern_type", DummySerializer(3)),
    ],
    1: [
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("resource_pattern_type", int8Serializer),
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
    ],
}


matchingAclSerializers: Dict[int, ClassSerializer[MatchingAcl]] = {
    version: ClassSerializer(MatchingAcl, schema) for version, schema in matchingAclSchemas.items()
}

matchingAclSerializers[-1] = matchingAclSerializers[1]


filterResponseSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("matching_acls", ArraySerializer(matchingAclSerializers[0])),
    ],
    1: [
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("matching_acls", ArraySerializer(matchingAclSerializers[1])),
    ],
}


filterResponseSerializers: Dict[int, ClassSerializer[FilterResponse]] = {
    version: ClassSerializer(FilterResponse, schema) for version, schema in filterResponseSchemas.items()
}

filterResponseSerializers[-1] = filterResponseSerializers[1]


deleteAclsResponseDataSchemas: Dict[int, Schema] = {
    0: [("throttle_time_ms", int32Serializer), ("filter_responses", ArraySerializer(filterResponseSerializers[0]))],
    1: [("throttle_time_ms", int32Serializer), ("filter_responses", ArraySerializer(filterResponseSerializers[1]))],
}


deleteAclsResponseDataSerializers: Dict[int, ClassSerializer[DeleteAclsResponseData]] = {
    version: ClassSerializer(DeleteAclsResponseData, schema)
    for version, schema in deleteAclsResponseDataSchemas.items()
}

deleteAclsResponseDataSerializers[-1] = deleteAclsResponseDataSerializers[1]
