##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.describe_delegation_token_request import DescribeDelegationTokenRequestData, Owner
from ._main_serializers import ArraySerializer, ClassSerializer, Schema, stringSerializer

ownerSchemas: Dict[int, Schema] = {
    0: [("principal_type", stringSerializer), ("name", stringSerializer)],
    1: [("principal_type", stringSerializer), ("name", stringSerializer)],
}


ownerSerializers: Dict[int, ClassSerializer[Owner]] = {
    version: ClassSerializer(Owner, schema) for version, schema in ownerSchemas.items()
}

ownerSerializers[-1] = ownerSerializers[1]


describeDelegationTokenRequestDataSchemas: Dict[int, Schema] = {
    0: [("owners", ArraySerializer(ownerSerializers[0]))],
    1: [("owners", ArraySerializer(ownerSerializers[1]))],
}


describeDelegationTokenRequestDataSerializers: Dict[int, ClassSerializer[DescribeDelegationTokenRequestData]] = {
    version: ClassSerializer(DescribeDelegationTokenRequestData, schema)
    for version, schema in describeDelegationTokenRequestDataSchemas.items()
}

describeDelegationTokenRequestDataSerializers[-1] = describeDelegationTokenRequestDataSerializers[1]
