##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.describe_log_dirs_request import (
    DescribeLogDirsRequestData,
    Topic,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int32Serializer,
    stringSerializer,
)


topicSchemas: Dict[int, Schema] = {
    0: [
        ('topic', stringSerializer),
        ('partitions', ArraySerializer(int32Serializer)),
    ],
    1: [
        ('topic', stringSerializer),
        ('partitions', ArraySerializer(int32Serializer)),
    ],
}


topicSerializers: Dict[int, DataClassSerializer[Topic]] = {
    version: DataClassSerializer(Topic, schema) for version, schema
    in topicSchemas.items()
}


describeLogDirsRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ('topics', ArraySerializer(topicSerializers[0])),
    ],
    1: [
        ('topics', ArraySerializer(topicSerializers[1])),
    ],
}


describeLogDirsRequestDataSerializers: Dict[int, DataClassSerializer[DescribeLogDirsRequestData]] = {
    version: DataClassSerializer(DescribeLogDirsRequestData, schema) for version, schema
    in describeLogDirsRequestDataSchemas.items()
}

