##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.describe_delegation_token_request import (
    DescribeDelegationTokenRequestData,
    Owner,
)

from ._main_serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    stringSerializer,
)


ownerSchemas: Dict[int, Schema] = {
    0: [("principal_type", stringSerializer), ("name", stringSerializer)],
    1: [("principal_type", stringSerializer), ("name", stringSerializer)],
}


ownerSerializers: Dict[int, DataClassSerializer[Owner]] = {
    version: DataClassSerializer(Owner, schema)
    for version, schema in ownerSchemas.items()
}


describeDelegationTokenRequestDataSchemas: Dict[int, Schema] = {
    0: [("owners", ArraySerializer(ownerSerializers[0]))],
    1: [("owners", ArraySerializer(ownerSerializers[1]))],
}


describeDelegationTokenRequestDataSerializers: Dict[
    int, DataClassSerializer[DescribeDelegationTokenRequestData]
] = {
    version: DataClassSerializer(DescribeDelegationTokenRequestData, schema)
    for version, schema in describeDelegationTokenRequestDataSchemas.items()
}
