##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.describe_acls_response import Acl, DescribeAclsResponseData, Resource

from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    aclOperationSerializer,
    aclPermissionTypeSerializer,
    errorCodeSerializer,
    int32Serializer,
    int8Serializer,
    nullableStringSerializer,
    resourceTypeSerializer,
    stringSerializer,
)


aclSchemas: Dict[int, Schema] = {
    0: [
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
    ],
    1: [
        ("principal", stringSerializer),
        ("host", stringSerializer),
        ("operation", aclOperationSerializer),
        ("permission_type", aclPermissionTypeSerializer),
    ],
}


aclSerializers: Dict[int, ClassSerializer[Acl]] = {
    version: ClassSerializer(Acl, schema) for version, schema in aclSchemas.items()
}

aclSerializers[-1] = aclSerializers[1]


resourceSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("acls", ArraySerializer(aclSerializers[0])),
        ("resource_pattern_type", DummySerializer(3)),
    ],
    1: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("resource_pattern_type", int8Serializer),
        ("acls", ArraySerializer(aclSerializers[1])),
    ],
}


resourceSerializers: Dict[int, ClassSerializer[Resource]] = {
    version: ClassSerializer(Resource, schema) for version, schema in resourceSchemas.items()
}

resourceSerializers[-1] = resourceSerializers[1]


describeAclsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("throttle_time_ms", int32Serializer),
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("resources", ArraySerializer(resourceSerializers[0])),
    ],
    1: [
        ("throttle_time_ms", int32Serializer),
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("resources", ArraySerializer(resourceSerializers[1])),
    ],
}


describeAclsResponseDataSerializers: Dict[int, ClassSerializer[DescribeAclsResponseData]] = {
    version: ClassSerializer(DescribeAclsResponseData, schema)
    for version, schema in describeAclsResponseDataSchemas.items()
}

describeAclsResponseDataSerializers[-1] = describeAclsResponseDataSerializers[1]
