##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.describe_log_dirs_request import DescribeLogDirsRequestData, Topic

from ._main_serializers import ArraySerializer, ClassSerializer, Schema, int32Serializer, stringSerializer


topicSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("partitions", ArraySerializer(int32Serializer))],
    1: [("topic", stringSerializer), ("partitions", ArraySerializer(int32Serializer))],
}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[1]


describeLogDirsRequestDataSchemas: Dict[int, Schema] = {
    0: [("topics", ArraySerializer(topicSerializers[0]))],
    1: [("topics", ArraySerializer(topicSerializers[1]))],
}


describeLogDirsRequestDataSerializers: Dict[int, ClassSerializer[DescribeLogDirsRequestData]] = {
    version: ClassSerializer(DescribeLogDirsRequestData, schema)
    for version, schema in describeLogDirsRequestDataSchemas.items()
}

describeLogDirsRequestDataSerializers[-1] = describeLogDirsRequestDataSerializers[1]
