##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.describe_groups_request import (
    DescribeGroupsRequestData,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    DummySerializer,
    Schema,
    booleanSerializer,
    stringSerializer,
)


describeGroupsRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ('groups', ArraySerializer(stringSerializer)),
        ('include_authorized_operations', DummySerializer(booleanSerializer.default)),
    ],
    1: [
        ('groups', ArraySerializer(stringSerializer)),
        ('include_authorized_operations', DummySerializer(booleanSerializer.default)),
    ],
    2: [
        ('groups', ArraySerializer(stringSerializer)),
        ('include_authorized_operations', DummySerializer(booleanSerializer.default)),
    ],
    3: [
        ('groups', ArraySerializer(stringSerializer)),
        ('include_authorized_operations', booleanSerializer),
    ],
}


describeGroupsRequestDataSerializers: Dict[int, DataClassSerializer[DescribeGroupsRequestData]] = {
    version: DataClassSerializer(DescribeGroupsRequestData, schema) for version, schema
    in describeGroupsRequestDataSchemas.items()
}

