###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.describe_configs_request import DescribeConfigsRequestData, Resource
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    booleanSerializer,
    resourceTypeSerializer,
    stringSerializer,
)

resourceSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("config_names", ArraySerializer(stringSerializer)),
    ],
    1: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("config_names", ArraySerializer(stringSerializer)),
    ],
    2: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("config_names", ArraySerializer(stringSerializer)),
    ],
}


resourceSerializers: Dict[int, ClassSerializer[Resource]] = {
    version: ClassSerializer(Resource, schema) for version, schema in resourceSchemas.items()
}

resourceSerializers[-1] = resourceSerializers[2]


describeConfigsRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("resources", ArraySerializer(resourceSerializers[0])),
        ("include_synonyms", DummySerializer(booleanSerializer.default)),
    ],
    1: [("resources", ArraySerializer(resourceSerializers[1])), ("include_synonyms", booleanSerializer)],
    2: [("resources", ArraySerializer(resourceSerializers[2])), ("include_synonyms", booleanSerializer)],
}


describeConfigsRequestDataSerializers: Dict[int, ClassSerializer[DescribeConfigsRequestData]] = {
    version: ClassSerializer(DescribeConfigsRequestData, schema)
    for version, schema in describeConfigsRequestDataSchemas.items()
}

describeConfigsRequestDataSerializers[-1] = describeConfigsRequestDataSerializers[2]
