##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.elect_preferred_leaders_request import (
    ElectPreferredLeadersRequestData,
    TopicPartition,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int32Serializer,
    stringSerializer,
)


topicPartitionSchemas: Dict[int, Schema] = {
    0: [
        ('topic', stringSerializer),
        ('partition_id', ArraySerializer(int32Serializer)),
    ],
}


topicPartitionSerializers: Dict[int, DataClassSerializer[TopicPartition]] = {
    version: DataClassSerializer(TopicPartition, schema) for version, schema
    in topicPartitionSchemas.items()
}


electPreferredLeadersRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ('topic_partitions', ArraySerializer(topicPartitionSerializers[0])),
        ('timeout_ms', int32Serializer),
    ],
}


electPreferredLeadersRequestDataSerializers: Dict[int, DataClassSerializer[ElectPreferredLeadersRequestData]] = {
    version: DataClassSerializer(ElectPreferredLeadersRequestData, schema) for version, schema
    in electPreferredLeadersRequestDataSchemas.items()
}

