###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.end_txn_request import EndTxnRequestData
from ._main_serializers import (
    ClassSerializer,
    Schema,
    booleanSerializer,
    int16Serializer,
    int64Serializer,
    stringSerializer,
)

endTxnRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("transactional_id", stringSerializer),
        ("producer_id", int64Serializer),
        ("producer_epoch", int16Serializer),
        ("transaction_result", booleanSerializer),
    ],
    1: [
        ("transactional_id", stringSerializer),
        ("producer_id", int64Serializer),
        ("producer_epoch", int16Serializer),
        ("transaction_result", booleanSerializer),
    ],
}


endTxnRequestDataSerializers: Dict[int, ClassSerializer[EndTxnRequestData]] = {
    version: ClassSerializer(EndTxnRequestData, schema) for version, schema in endTxnRequestDataSchemas.items()
}

endTxnRequestDataSerializers[-1] = endTxnRequestDataSerializers[1]
