##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.end_txn_response import EndTxnResponseData

from ._main_serializers import (
    DataClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
)


endTxnResponseDataSchemas: Dict[int, Schema] = {
    0: [("throttle_time_ms", int32Serializer), ("error_code", errorCodeSerializer)],
    1: [("throttle_time_ms", int32Serializer), ("error_code", errorCodeSerializer)],
}


endTxnResponseDataSerializers: Dict[int, DataClassSerializer[EndTxnResponseData]] = {
    version: DataClassSerializer(EndTxnResponseData, schema)
    for version, schema in endTxnResponseDataSchemas.items()
}
