##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.expire_delegation_token_request import ExpireDelegationTokenRequestData
from ._main_serializers import ClassSerializer, Schema, bytesSerializer, int64Serializer

expireDelegationTokenRequestDataSchemas: Dict[int, Schema] = {
    0: [("hmac", bytesSerializer), ("expiry_time_period", int64Serializer)],
    1: [("hmac", bytesSerializer), ("expiry_time_period", int64Serializer)],
}


expireDelegationTokenRequestDataSerializers: Dict[int, ClassSerializer[ExpireDelegationTokenRequestData]] = {
    version: ClassSerializer(ExpireDelegationTokenRequestData, schema)
    for version, schema in expireDelegationTokenRequestDataSchemas.items()
}

expireDelegationTokenRequestDataSerializers[-1] = expireDelegationTokenRequestDataSerializers[1]
