##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.find_coordinator_request import (
    FindCoordinatorRequestData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    DummySerializer,
    Schema,
    int8Serializer,
    stringSerializer,
)


findCoordinatorRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("key", stringSerializer),
        ("key_type", DummySerializer(int8Serializer.default)),
    ],
    1: [("key", stringSerializer), ("key_type", int8Serializer)],
    2: [("key", stringSerializer), ("key_type", int8Serializer)],
}


findCoordinatorRequestDataSerializers: Dict[
    int, DataClassSerializer[FindCoordinatorRequestData]
] = {
    version: DataClassSerializer(FindCoordinatorRequestData, schema)
    for version, schema in findCoordinatorRequestDataSchemas.items()
}
