##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.heartbeat_request import HeartbeatRequestData
from ._main_serializers import (
    ClassSerializer,
    DummySerializer,
    Schema,
    int32Serializer,
    nullableStringSerializer,
    stringSerializer,
)

heartbeatRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    1: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    2: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    3: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("group_instance_id", nullableStringSerializer),
    ],
}


heartbeatRequestDataSerializers: Dict[int, ClassSerializer[HeartbeatRequestData]] = {
    version: ClassSerializer(HeartbeatRequestData, schema) for version, schema in heartbeatRequestDataSchemas.items()
}

heartbeatRequestDataSerializers[-1] = heartbeatRequestDataSerializers[3]
