##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.heartbeat_response import HeartbeatResponseData

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    DummySerializer,
    Schema,
    int16Serializer,
    int32Serializer,
)


heartbeatResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", int16Serializer),
        ("throttle_time_ms", DummySerializer(int32Serializer.default)),
    ],
    1: [("throttle_time_ms", int32Serializer), ("error_code", int16Serializer)],
    2: [("throttle_time_ms", int32Serializer), ("error_code", int16Serializer)],
    3: [("throttle_time_ms", int32Serializer), ("error_code", int16Serializer)],
}


heartbeatResponseDataSerializers: Dict[
    int, DataClassSerializer[HeartbeatResponseData]
] = {
    version: DataClassSerializer(HeartbeatResponseData, schema)
    for version, schema in heartbeatResponseDataSchemas.items()
}
