##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.incremental_alter_configs_response import (
    IncrementalAlterConfigsResponseData,
    Response,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int16Serializer,
    int32Serializer,
    int8Serializer,
    nullableStringSerializer,
    stringSerializer,
)


responseSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", int16Serializer),
        ("error_message", nullableStringSerializer),
        ("resource_type", int8Serializer),
        ("resource_name", stringSerializer),
    ]
}


responseSerializers: Dict[int, DataClassSerializer[Response]] = {
    version: DataClassSerializer(Response, schema)
    for version, schema in responseSchemas.items()
}


incrementalAlterConfigsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("throttle_time_ms", int32Serializer),
        ("responses", ArraySerializer(responseSerializers[0])),
    ]
}


incrementalAlterConfigsResponseDataSerializers: Dict[
    int, DataClassSerializer[IncrementalAlterConfigsResponseData]
] = {
    version: DataClassSerializer(IncrementalAlterConfigsResponseData, schema)
    for version, schema in incrementalAlterConfigsResponseDataSchemas.items()
}
