##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.incremental_alter_configs_response import IncrementalAlterConfigsResponseData, Response
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    nullableStringSerializer,
    resourceTypeSerializer,
    stringSerializer,
)

responseSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("error_message", nullableStringSerializer),
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
    ]
}


responseSerializers: Dict[int, ClassSerializer[Response]] = {
    version: ClassSerializer(Response, schema) for version, schema in responseSchemas.items()
}

responseSerializers[-1] = responseSerializers[0]


incrementalAlterConfigsResponseDataSchemas: Dict[int, Schema] = {
    0: [("throttle_time_ms", int32Serializer), ("responses", ArraySerializer(responseSerializers[0]))]
}


incrementalAlterConfigsResponseDataSerializers: Dict[int, ClassSerializer[IncrementalAlterConfigsResponseData]] = {
    version: ClassSerializer(IncrementalAlterConfigsResponseData, schema)
    for version, schema in incrementalAlterConfigsResponseDataSchemas.items()
}

incrementalAlterConfigsResponseDataSerializers[-1] = incrementalAlterConfigsResponseDataSerializers[0]
