##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.incremental_alter_configs_request import (
    Config,
    IncrementalAlterConfigsRequestData,
    Resource,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    booleanSerializer,
    int8Serializer,
    nullableStringSerializer,
    stringSerializer,
)


configSchemas: Dict[int, Schema] = {
    0: [
        ("name", stringSerializer),
        ("config_operation", int8Serializer),
        ("value", nullableStringSerializer),
    ]
}


configSerializers: Dict[int, DataClassSerializer[Config]] = {
    version: DataClassSerializer(Config, schema)
    for version, schema in configSchemas.items()
}


resourceSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", int8Serializer),
        ("resource_name", stringSerializer),
        ("configs", ArraySerializer(configSerializers[0])),
    ]
}


resourceSerializers: Dict[int, DataClassSerializer[Resource]] = {
    version: DataClassSerializer(Resource, schema)
    for version, schema in resourceSchemas.items()
}


incrementalAlterConfigsRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("resources", ArraySerializer(resourceSerializers[0])),
        ("validate_only", booleanSerializer),
    ]
}


incrementalAlterConfigsRequestDataSerializers: Dict[
    int, DataClassSerializer[IncrementalAlterConfigsRequestData]
] = {
    version: DataClassSerializer(IncrementalAlterConfigsRequestData, schema)
    for version, schema in incrementalAlterConfigsRequestDataSchemas.items()
}
