##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.incremental_alter_configs_request import Config, IncrementalAlterConfigsRequestData, Resource
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    booleanSerializer,
    int8Serializer,
    nullableStringSerializer,
    resourceTypeSerializer,
    stringSerializer,
)

configSchemas: Dict[int, Schema] = {
    0: [("name", stringSerializer), ("config_operation", int8Serializer), ("value", nullableStringSerializer)]
}


configSerializers: Dict[int, ClassSerializer[Config]] = {
    version: ClassSerializer(Config, schema) for version, schema in configSchemas.items()
}

configSerializers[-1] = configSerializers[0]


resourceSchemas: Dict[int, Schema] = {
    0: [
        ("resource_type", resourceTypeSerializer),
        ("resource_name", stringSerializer),
        ("configs", ArraySerializer(configSerializers[0])),
    ]
}


resourceSerializers: Dict[int, ClassSerializer[Resource]] = {
    version: ClassSerializer(Resource, schema) for version, schema in resourceSchemas.items()
}

resourceSerializers[-1] = resourceSerializers[0]


incrementalAlterConfigsRequestDataSchemas: Dict[int, Schema] = {
    0: [("resources", ArraySerializer(resourceSerializers[0])), ("validate_only", booleanSerializer)]
}


incrementalAlterConfigsRequestDataSerializers: Dict[int, ClassSerializer[IncrementalAlterConfigsRequestData]] = {
    version: ClassSerializer(IncrementalAlterConfigsRequestData, schema)
    for version, schema in incrementalAlterConfigsRequestDataSchemas.items()
}

incrementalAlterConfigsRequestDataSerializers[-1] = incrementalAlterConfigsRequestDataSerializers[0]
