##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.init_producer_id_response import (
    InitProducerIdResponseData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    Schema,
    int16Serializer,
    int32Serializer,
    int64Serializer,
)


initProducerIdResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
        ('producer_id', int64Serializer),
        ('producer_epoch', int16Serializer),
    ],
    1: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
        ('producer_id', int64Serializer),
        ('producer_epoch', int16Serializer),
    ],
}


initProducerIdResponseDataSerializers: Dict[int, DataClassSerializer[InitProducerIdResponseData]] = {
    version: DataClassSerializer(InitProducerIdResponseData, schema) for version, schema
    in initProducerIdResponseDataSchemas.items()
}

