##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.leader_and_isr_response import LeaderAndIsrResponseData, Partition

from ._main_serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", errorCodeSerializer),
    ],
    1: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", errorCodeSerializer),
    ],
    2: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", errorCodeSerializer),
    ],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


leaderAndIsrResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("error_code", errorCodeSerializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
    2: [
        ("error_code", errorCodeSerializer),
        ("partitions", ArraySerializer(partitionSerializers[2])),
    ],
}


leaderAndIsrResponseDataSerializers: Dict[
    int, DataClassSerializer[LeaderAndIsrResponseData]
] = {
    version: DataClassSerializer(LeaderAndIsrResponseData, schema)
    for version, schema in leaderAndIsrResponseDataSchemas.items()
}
