##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.leader_and_isr_response import (
    LeaderAndIsrResponseData,
    Partition,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int16Serializer,
    int32Serializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", int16Serializer),
    ],
    1: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", int16Serializer),
    ],
    2: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", int16Serializer),
    ],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


leaderAndIsrResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", int16Serializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("error_code", int16Serializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
    2: [
        ("error_code", int16Serializer),
        ("partitions", ArraySerializer(partitionSerializers[2])),
    ],
}


leaderAndIsrResponseDataSerializers: Dict[
    int, DataClassSerializer[LeaderAndIsrResponseData]
] = {
    version: DataClassSerializer(LeaderAndIsrResponseData, schema)
    for version, schema in leaderAndIsrResponseDataSchemas.items()
}
