##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.leave_group_request import LeaveGroupRequestData

from ._main_serializers import DataClassSerializer, Schema, stringSerializer


leaveGroupRequestDataSchemas: Dict[int, Schema] = {
    0: [("group_id", stringSerializer), ("member_id", stringSerializer)],
    1: [("group_id", stringSerializer), ("member_id", stringSerializer)],
    2: [("group_id", stringSerializer), ("member_id", stringSerializer)],
}


leaveGroupRequestDataSerializers: Dict[
    int, DataClassSerializer[LeaveGroupRequestData]
] = {
    version: DataClassSerializer(LeaveGroupRequestData, schema)
    for version, schema in leaveGroupRequestDataSchemas.items()
}
