##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.list_groups_request import (
    ListGroupsRequestData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    Schema,
)


listGroupsRequestDataSchemas: Dict[int, Schema] = {
    0: [
    ],
    1: [
    ],
    2: [
    ],
}


listGroupsRequestDataSerializers: Dict[int, DataClassSerializer[ListGroupsRequestData]] = {
    version: DataClassSerializer(ListGroupsRequestData, schema) for version, schema
    in listGroupsRequestDataSchemas.items()
}

