###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.list_groups_response import Group, ListGroupsResponseData
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    stringSerializer,
)

groupSchemas: Dict[int, Schema] = {
    0: [("group_id", stringSerializer), ("protocol_type", stringSerializer)],
    1: [("group_id", stringSerializer), ("protocol_type", stringSerializer)],
    2: [("group_id", stringSerializer), ("protocol_type", stringSerializer)],
}


groupSerializers: Dict[int, ClassSerializer[Group]] = {
    version: ClassSerializer(Group, schema) for version, schema in groupSchemas.items()
}

groupSerializers[-1] = groupSerializers[2]


listGroupsResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("groups", ArraySerializer(groupSerializers[0])),
        ("throttle_time_ms", DummySerializer(0)),
    ],
    1: [
        ("throttle_time_ms", int32Serializer),
        ("error_code", errorCodeSerializer),
        ("groups", ArraySerializer(groupSerializers[1])),
    ],
    2: [
        ("throttle_time_ms", int32Serializer),
        ("error_code", errorCodeSerializer),
        ("groups", ArraySerializer(groupSerializers[2])),
    ],
}


listGroupsResponseDataSerializers: Dict[int, ClassSerializer[ListGroupsResponseData]] = {
    version: ClassSerializer(ListGroupsResponseData, schema)
    for version, schema in listGroupsResponseDataSchemas.items()
}

listGroupsResponseDataSerializers[-1] = listGroupsResponseDataSerializers[2]
