###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.offset_for_leader_epoch_request import OffsetForLeaderEpochRequestData, Partition, Topic
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    DummySerializer,
    Schema,
    int32Serializer,
    stringSerializer,
)

partitionSchemas: Dict[int, Schema] = {
    0: [
        ("partition", int32Serializer),
        ("leader_epoch", int32Serializer),
        ("current_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    1: [
        ("partition", int32Serializer),
        ("leader_epoch", int32Serializer),
        ("current_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    2: [("partition", int32Serializer), ("current_leader_epoch", int32Serializer), ("leader_epoch", int32Serializer)],
    3: [("partition", int32Serializer), ("current_leader_epoch", int32Serializer), ("leader_epoch", int32Serializer)],
}


partitionSerializers: Dict[int, ClassSerializer[Partition]] = {
    version: ClassSerializer(Partition, schema) for version, schema in partitionSchemas.items()
}

partitionSerializers[-1] = partitionSerializers[3]


topicSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[0]))],
    1: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[1]))],
    2: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[2]))],
    3: [("topic", stringSerializer), ("partitions", ArraySerializer(partitionSerializers[3]))],
}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[3]


offsetForLeaderEpochRequestDataSchemas: Dict[int, Schema] = {
    0: [("topics", ArraySerializer(topicSerializers[0])), ("replica_id", DummySerializer(int32Serializer.default))],
    1: [("topics", ArraySerializer(topicSerializers[1])), ("replica_id", DummySerializer(int32Serializer.default))],
    2: [("topics", ArraySerializer(topicSerializers[2])), ("replica_id", DummySerializer(int32Serializer.default))],
    3: [("replica_id", int32Serializer), ("topics", ArraySerializer(topicSerializers[3]))],
}


offsetForLeaderEpochRequestDataSerializers: Dict[int, ClassSerializer[OffsetForLeaderEpochRequestData]] = {
    version: ClassSerializer(OffsetForLeaderEpochRequestData, schema)
    for version, schema in offsetForLeaderEpochRequestDataSchemas.items()
}

offsetForLeaderEpochRequestDataSerializers[-1] = offsetForLeaderEpochRequestDataSerializers[3]
