##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.offset_commit_request import (
    OffsetCommitRequestData,
    Partition,
    Topic,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    DummySerializer,
    Schema,
    int32Serializer,
    int64Serializer,
    nullableStringSerializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    1: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        (None, int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    2: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    3: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    4: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    5: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_metadata", nullableStringSerializer),
        ("committed_leader_epoch", DummySerializer(int32Serializer.default)),
    ],
    6: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_leader_epoch", int32Serializer),
        ("committed_metadata", nullableStringSerializer),
    ],
    7: [
        ("partition_index", int32Serializer),
        ("committed_offset", int64Serializer),
        ("committed_leader_epoch", int32Serializer),
        ("committed_metadata", nullableStringSerializer),
    ],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


topicSchemas: Dict[int, Schema] = {
    0: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
    2: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[2])),
    ],
    3: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[3])),
    ],
    4: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[4])),
    ],
    5: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[5])),
    ],
    6: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[6])),
    ],
    7: [
        ("name", stringSerializer),
        ("partitions", ArraySerializer(partitionSerializers[7])),
    ],
}


topicSerializers: Dict[int, DataClassSerializer[Topic]] = {
    version: DataClassSerializer(Topic, schema)
    for version, schema in topicSchemas.items()
}


offsetCommitRequestDataSchemas: Dict[int, Schema] = {
    0: [
        ("group_id", stringSerializer),
        ("topics", ArraySerializer(topicSerializers[0])),
        ("generation_id", DummySerializer(int32Serializer.default)),
        ("member_id", DummySerializer(stringSerializer.default)),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    1: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("topics", ArraySerializer(topicSerializers[1])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    2: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        (None, int64Serializer),
        ("topics", ArraySerializer(topicSerializers[2])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    3: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        (None, int64Serializer),
        ("topics", ArraySerializer(topicSerializers[3])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    4: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        (None, int64Serializer),
        ("topics", ArraySerializer(topicSerializers[4])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    5: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("topics", ArraySerializer(topicSerializers[5])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    6: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("topics", ArraySerializer(topicSerializers[6])),
        ("group_instance_id", DummySerializer(nullableStringSerializer.default)),
    ],
    7: [
        ("group_id", stringSerializer),
        ("generation_id", int32Serializer),
        ("member_id", stringSerializer),
        ("group_instance_id", nullableStringSerializer),
        ("topics", ArraySerializer(topicSerializers[7])),
    ],
}


offsetCommitRequestDataSerializers: Dict[
    int, DataClassSerializer[OffsetCommitRequestData]
] = {
    version: DataClassSerializer(OffsetCommitRequestData, schema)
    for version, schema in offsetCommitRequestDataSchemas.items()
}
