##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.renew_delegation_token_request import (
    RenewDelegationTokenRequestData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    Schema,
    bytesSerializer,
    int64Serializer,
)


renewDelegationTokenRequestDataSchemas: Dict[int, Schema] = {
    0: [("hmac", bytesSerializer), ("renew_time_period", int64Serializer)],
    1: [("hmac", bytesSerializer), ("renew_time_period", int64Serializer)],
}


renewDelegationTokenRequestDataSerializers: Dict[
    int, DataClassSerializer[RenewDelegationTokenRequestData]
] = {
    version: DataClassSerializer(RenewDelegationTokenRequestData, schema)
    for version, schema in renewDelegationTokenRequestDataSchemas.items()
}
