##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict

from ...structs.api.renew_delegation_token_response import RenewDelegationTokenResponseData
from ._main_serializers import ClassSerializer, Schema, errorCodeSerializer, int32Serializer, int64Serializer

renewDelegationTokenResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("expiry_timestamp", int64Serializer),
        ("throttle_time_ms", int32Serializer),
    ],
    1: [
        ("error_code", errorCodeSerializer),
        ("expiry_timestamp", int64Serializer),
        ("throttle_time_ms", int32Serializer),
    ],
}


renewDelegationTokenResponseDataSerializers: Dict[int, ClassSerializer[RenewDelegationTokenResponseData]] = {
    version: ClassSerializer(RenewDelegationTokenResponseData, schema)
    for version, schema in renewDelegationTokenResponseDataSchemas.items()
}

renewDelegationTokenResponseDataSerializers[-1] = renewDelegationTokenResponseDataSerializers[1]
