###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.sasl_handshake_request import SaslHandshakeRequestData
from ._main_serializers import ClassSerializer, Schema, stringSerializer

saslHandshakeRequestDataSchemas: Dict[int, Schema] = {
    0: [("mechanism", stringSerializer)],
    1: [("mechanism", stringSerializer)],
}


saslHandshakeRequestDataSerializers: Dict[int, ClassSerializer[SaslHandshakeRequestData]] = {
    version: ClassSerializer(SaslHandshakeRequestData, schema)
    for version, schema in saslHandshakeRequestDataSchemas.items()
}

saslHandshakeRequestDataSerializers[-1] = saslHandshakeRequestDataSerializers[1]
