##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.sasl_handshake_response import (
    SaslHandshakeResponseData,
)

from esque_wire.protocol.serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    int16Serializer,
    stringSerializer,
)


saslHandshakeResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ('error_code', int16Serializer),
        ('mechanisms', ArraySerializer(stringSerializer)),
    ],
    1: [
        ('error_code', int16Serializer),
        ('mechanisms', ArraySerializer(stringSerializer)),
    ],
}


saslHandshakeResponseDataSerializers: Dict[int, DataClassSerializer[SaslHandshakeResponseData]] = {
    version: DataClassSerializer(SaslHandshakeResponseData, schema) for version, schema
    in saslHandshakeResponseDataSchemas.items()
}

