##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.sasl_authenticate_response import (
    SaslAuthenticateResponseData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    DummySerializer,
    Schema,
    bytesSerializer,
    int16Serializer,
    int64Serializer,
    nullableStringSerializer,
)


saslAuthenticateResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ('error_code', int16Serializer),
        ('error_message', nullableStringSerializer),
        ('auth_bytes', bytesSerializer),
        ('session_lifetime_ms', DummySerializer(int64Serializer.default)),
    ],
    1: [
        ('error_code', int16Serializer),
        ('error_message', nullableStringSerializer),
        ('auth_bytes', bytesSerializer),
        ('session_lifetime_ms', int64Serializer),
    ],
}


saslAuthenticateResponseDataSerializers: Dict[int, DataClassSerializer[SaslAuthenticateResponseData]] = {
    version: DataClassSerializer(SaslAuthenticateResponseData, schema) for version, schema
    in saslAuthenticateResponseDataSchemas.items()
}

