##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.sasl_handshake_request import SaslHandshakeRequestData

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    Schema,
    stringSerializer,
)


saslHandshakeRequestDataSchemas: Dict[int, Schema] = {
    0: [("mechanism", stringSerializer)],
    1: [("mechanism", stringSerializer)],
}


saslHandshakeRequestDataSerializers: Dict[
    int, DataClassSerializer[SaslHandshakeRequestData]
] = {
    version: DataClassSerializer(SaslHandshakeRequestData, schema)
    for version, schema in saslHandshakeRequestDataSchemas.items()
}
