##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.stop_replica_response import Partition, StopReplicaResponseData

from ._main_serializers import (
    ArraySerializer,
    DataClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    stringSerializer,
)


partitionSchemas: Dict[int, Schema] = {
    0: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", errorCodeSerializer),
    ],
    1: [
        ("topic", stringSerializer),
        ("partition", int32Serializer),
        ("error_code", errorCodeSerializer),
    ],
}


partitionSerializers: Dict[int, DataClassSerializer[Partition]] = {
    version: DataClassSerializer(Partition, schema)
    for version, schema in partitionSchemas.items()
}


stopReplicaResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ("error_code", errorCodeSerializer),
        ("partitions", ArraySerializer(partitionSerializers[0])),
    ],
    1: [
        ("error_code", errorCodeSerializer),
        ("partitions", ArraySerializer(partitionSerializers[1])),
    ],
}


stopReplicaResponseDataSerializers: Dict[
    int, DataClassSerializer[StopReplicaResponseData]
] = {
    version: DataClassSerializer(StopReplicaResponseData, schema)
    for version, schema in stopReplicaResponseDataSchemas.items()
}
