###############################################################
# Autogenerated module. Please don't modify.                  #
# Edit according file in protocol_generator/templates instead #
###############################################################

from typing import Dict

from ...structs.api.stop_replica_response import Partition, StopReplicaResponseData
from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    errorCodeSerializer,
    int32Serializer,
    stringSerializer,
)

partitionSchemas: Dict[int, Schema] = {
    0: [("topic", stringSerializer), ("partition", int32Serializer), ("error_code", errorCodeSerializer)],
    1: [("topic", stringSerializer), ("partition", int32Serializer), ("error_code", errorCodeSerializer)],
}


partitionSerializers: Dict[int, ClassSerializer[Partition]] = {
    version: ClassSerializer(Partition, schema) for version, schema in partitionSchemas.items()
}

partitionSerializers[-1] = partitionSerializers[1]


stopReplicaResponseDataSchemas: Dict[int, Schema] = {
    0: [("error_code", errorCodeSerializer), ("partitions", ArraySerializer(partitionSerializers[0]))],
    1: [("error_code", errorCodeSerializer), ("partitions", ArraySerializer(partitionSerializers[1]))],
}


stopReplicaResponseDataSerializers: Dict[int, ClassSerializer[StopReplicaResponseData]] = {
    version: ClassSerializer(StopReplicaResponseData, schema)
    for version, schema in stopReplicaResponseDataSchemas.items()
}

stopReplicaResponseDataSerializers[-1] = stopReplicaResponseDataSerializers[1]
