##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from esque_wire.protocol.structs.sync_group_response import (
    SyncGroupResponseData,
)

from esque_wire.protocol.serializers import (
    DataClassSerializer,
    DummySerializer,
    Schema,
    bytesSerializer,
    int16Serializer,
    int32Serializer,
)


syncGroupResponseDataSchemas: Dict[int, Schema] = {
    0: [
        ('error_code', int16Serializer),
        ('assignment', bytesSerializer),
        ('throttle_time_ms', DummySerializer(int32Serializer.default)),
    ],
    1: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
        ('assignment', bytesSerializer),
    ],
    2: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
        ('assignment', bytesSerializer),
    ],
    3: [
        ('throttle_time_ms', int32Serializer),
        ('error_code', int16Serializer),
        ('assignment', bytesSerializer),
    ],
}


syncGroupResponseDataSerializers: Dict[int, DataClassSerializer[SyncGroupResponseData]] = {
    version: DataClassSerializer(SyncGroupResponseData, schema) for version, schema
    in syncGroupResponseDataSchemas.items()
}

