##############################################
# Autogenerated module. Please don't modify. #
##############################################

from typing import Dict
from ...structs.api.write_txn_markers_request import Topic, TransactionMarker, WriteTxnMarkersRequestData

from ._main_serializers import (
    ArraySerializer,
    ClassSerializer,
    Schema,
    booleanSerializer,
    int16Serializer,
    int32Serializer,
    int64Serializer,
    stringSerializer,
)


topicSchemas: Dict[int, Schema] = {0: [("topic", stringSerializer), ("partitions", ArraySerializer(int32Serializer))]}


topicSerializers: Dict[int, ClassSerializer[Topic]] = {
    version: ClassSerializer(Topic, schema) for version, schema in topicSchemas.items()
}

topicSerializers[-1] = topicSerializers[0]


transactionMarkerSchemas: Dict[int, Schema] = {
    0: [
        ("producer_id", int64Serializer),
        ("producer_epoch", int16Serializer),
        ("transaction_result", booleanSerializer),
        ("topics", ArraySerializer(topicSerializers[0])),
        ("coordinator_epoch", int32Serializer),
    ]
}


transactionMarkerSerializers: Dict[int, ClassSerializer[TransactionMarker]] = {
    version: ClassSerializer(TransactionMarker, schema) for version, schema in transactionMarkerSchemas.items()
}

transactionMarkerSerializers[-1] = transactionMarkerSerializers[0]


writeTxnMarkersRequestDataSchemas: Dict[int, Schema] = {
    0: [("transaction_markers", ArraySerializer(transactionMarkerSerializers[0]))]
}


writeTxnMarkersRequestDataSerializers: Dict[int, ClassSerializer[WriteTxnMarkersRequestData]] = {
    version: ClassSerializer(WriteTxnMarkersRequestData, schema)
    for version, schema in writeTxnMarkersRequestDataSchemas.items()
}

writeTxnMarkersRequestDataSerializers[-1] = writeTxnMarkersRequestDataSerializers[0]
